name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        env:
          GATSBY_WP_BASE_URL: ${{ secrets.GATSBY_WP_BASE_URL }}
          GATSBY_WP_PROTOCOL: ${{ secrets.GATSBY_WP_PROTOCOL }}
        with:
          access-token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
